[workspace]
members = [
    "node",
    "consensus",
    "runtime",
    "crypto",
    "storage",
    "types",
    "wallet",
    "state",
    "mempool",
    "rpc",
    "cli-wallet",
    "explorer",
    "staking"
]

[profile.release]
opt-level = 3
