[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
types = { path = "../types" }
anyhow = "1"
