[package]
name = "mempool"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
crypto = { path = "../crypto" }
state = { path = "../state" }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tokio = { version = "1", features = ["full"] }
